"use client";
import { timeAgo } from "@/lib/simulation";

export default function ReportsPage({ reports, onGenerate, generating }) {
  return (
    <div className="panel">
      <div className="panel-head">
        <h2>Shift &amp; incident reports</h2>
        <button
          className="btn btn-primary"
          style={{ width: "auto", marginTop: 0, padding: "8px 14px", fontSize: 12.5 }}
          onClick={onGenerate}
          disabled={generating}
        >
          {generating ? "Generating\u2026" : "Generate shift report"}
        </button>
      </div>
      {reports.length ? (
        <div>
          {reports.map((r) => (
            <div className="report-item" key={r.id}>
              <div>
                <div className="r-title">{r.title}</div>
                <div className="r-meta">
                  Generated by {r.generatedBy} &middot; {timeAgo(r.createdAt)}
                </div>
              </div>
              <div className="r-stats">
                Open {r.openCount} &middot; Investigating {r.investigating} &middot; Contained {r.contained}{" "}
                &middot; Resolved {r.resolved}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="empty-state">No reports generated yet this session.</div>
      )}
    </div>
  );
}
